### ISSUE TITLE
hypergeometric test fails for python 3.10

### ISSUE THREAD

**Issue by jharlow-intel** [IntelPython/mkl_random#25]
Greetings!

Sorry I could not provide a PR, for I'm not sure what exactly the nature of the problem is, but:

When running the `test_random.py`  test suite, for versions <3.10 of python, it executes and works fine:
```
(python-39) harlowjo@harlowjo-mobl:~/temp/lib/python3.10/site-packages/mkl_random/tests$ python3 --version
Python 3.9.13
(python-39) harlowjo@harlowjo-mobl:~/temp/lib/python3.10/site-packages/mkl_random/tests$ python3 test_random.py
.................................................................................
----------------------------------------------------------------------
Ran 81 tests in 0.191s

OK
```

When running on python 3.10, however:

```
(python-310) harlowjo@harlowjo-mobl:~/temp/lib/python3.10/site-packages/mkl_random/tests$ python3 --version
Python 3.10.6
(python-310) harlowjo@harlowjo-mobl:~/temp/lib/python3.10/site-packages/mkl_random/tests$ python3 test_random.py
..............................E..................................................
======================================================================
ERROR: test_hypergeometric (mkl_random.tests.test_random.TestRandomDist_Intel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harlowjo/temp/lib/python3.10/site-packages/mkl_random/tests/test_random.py", line 579, in test_hypergeometric
    actual = rnd.hypergeometric(10.1, 5.5, 14, size=(3, 2))
  File "mkl_random/mklrand.pyx", line 5047, in mkl_random.mklrand.RandomState.hypergeometric
TypeError: Cannot convert numpy.int64 to numpy.ndarray

----------------------------------------------------------------------
Ran 81 tests in 0.194s

FAILED (errors=1)
```

I attempted different versions of `numpy` that are compatible with python 3.10 as well but it fails for python 3.10 regardless of what numpy version is used.

Information:

Test line throwing: https://github.com/IntelPython/mkl_random/blob/780fde9c24da89f9ec24d5ee70657c83d8a6aeaa/mkl_random/tests/test_random.py#L578
Source line: 
https://github.com/IntelPython/mkl_random/blob/780fde9c24da89f9ec24d5ee70657c83d8a6aeaa/mkl_random/mklrand.pyx#L5047

mkl_random version: v1.22.post2 (but this occurs on `master` as well)

Operating System: 
```
(python-310) harlowjo@harlowjo-mobl:~/repositories/IntelPython/mkl_random/mkl_random/tests$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

If I'm doing anything wrong, let me know! Currently this is blocking our Teamcity CI from completing recipe builds for python 3.10

**Comment by ekomarova** [comment]
This error occurs because you are using the wrong commit for 3.10. This problem has already been fixed in git_rev: b57e56534c83d67b3a6d34b244f79d5ca2d3faf8

**Comment by jharlow-intel** [comment]
> This error occurs because you are using the wrong commit for 3.10. This problem has already been fixed in git_rev: [b57e565](https://github.com/IntelPython/mkl_random/commit/b57e56534c83d67b3a6d34b244f79d5ca2d3faf8)

I tried `master` though and it still fails. I went ahead and checked out that commit itself and it fails the same way. Am I doing something else wrong?

```
(python-310) harlowjo@harlowjo-mobl:~/repositories/IntelPython/mkl_random$ git checkout b57e56534c83d67b3a6d34b244f79d5ca2d3faf8
Note: switching to 'b57e56534c83d67b3a6d34b244f79d5ca2d3faf8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b57e565 Merge pull request #23 from IntelPython/fix-sat-5359

(python-310) harlowjo@harlowjo-mobl:~/repositories/IntelPython/mkl_random/mkl_random/tests$ python3 test_random.py
..............................E...................................................
======================================================================
ERROR: test_hypergeometric (mkl_random.tests.test_random.TestRandomDist_Intel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harlowjo/repositories/IntelPython/mkl_random/mkl_random/tests/test_random.py", line 577, in test_hypergeometric
    actual = rnd.hypergeometric(10.1, 5.5, 14, size=(3, 2))
  File "mkl_random/mklrand.pyx", line 5047, in mkl_random.mklrand.RandomState.hypergeometric
TypeError: Cannot convert numpy.int64 to numpy.ndarray

----------------------------------------------------------------------
Ran 82 tests in 0.398s

FAILED (errors=1)
```

**Comment by ekomarova** [comment]
For this to work, you need to rebuild numpy again with  mkl_random rev [b57e565](https://github.com/IntelPython/mkl_random/commit/b57e56534c83d67b3a6d34b244f79d5ca2d3faf8) and then launch the tests
